[2024-07-08T15:42:44.222+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T15:42:44.260+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.taschik scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-08T15:42:44.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.taschik scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-08T15:42:44.276+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-07-08T15:42:44.297+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): taschik> on 2024-07-08 00:00:00+00:00
[2024-07-08T15:42:44.308+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=309) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T15:42:44.310+0000] {standard_task_runner.py:63} INFO - Started process 313 to run task
[2024-07-08T15:42:44.314+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'taschik', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '472', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpc7a_w01q']
[2024-07-08T15:42:44.318+0000] {standard_task_runner.py:91} INFO - Job 472: Subtask taschik
[2024-07-08T15:42:44.403+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.taschik scheduled__2024-07-08T00:00:00+00:00 [running]> on host 4a510a860371
[2024-07-08T15:42:44.610+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dad' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='taschik' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-08T15:42:44.614+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T15:42:44.615+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS tab(
                id int,
                sosi TEXT
            );        
        
[2024-07-08T15:42:44.636+0000] {base.py:84} INFO - Using connection ID 'books_connection' for task execution.
[2024-07-08T15:42:44.675+0000] {base.py:84} INFO - Using connection ID 'books_connection' for task execution.
[2024-07-08T15:42:44.681+0000] {sql.py:487} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS tab(
                id int,
                sosi TEXT
            );        
        , parameters: None
[2024-07-08T15:42:44.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T15:42:44.735+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(tab, 2200) already exists.

[2024-07-08T15:42:44.785+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=taschik, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240708T154244, end_date=20240708T154244
[2024-07-08T15:42:44.822+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 472 for task taschik (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(tab, 2200) already exists.
; 313)
[2024-07-08T15:42:44.893+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T15:42:44.921+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-08T15:42:44.954+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T15:42:44.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
