[2024-07-08T15:42:13.515+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_pipeline.taschik scheduled__2024-07-08T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
