[2024-07-10T13:37:41.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T13:37:41.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T13:37:41.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T13:37:41.994+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 10
[2024-07-10T13:37:42.179+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): loading_into_db> on 2024-07-09 00:00:00+00:00
[2024-07-10T13:37:42.187+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1488) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T13:37:42.189+0000] {standard_task_runner.py:63} INFO - Started process 1490 to run task
[2024-07-10T13:37:42.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'loading_into_db', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_al8knov']
[2024-07-10T13:37:42.192+0000] {standard_task_runner.py:91} INFO - Job 593: Subtask loading_into_db
[2024-07-10T13:37:42.247+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [running]> on host afe5e479c9b4
[2024-07-10T13:37:42.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='loading_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T13:37:42.341+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T13:37:42.389+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T13:37:42.390+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 71, in load_charachteristics
    cur.execute(
psycopg2.errors.UndefinedFile: could not open file "/opt/***/dags/charachteristics.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2024-07-10T13:37:42.410+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=loading_into_db, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T133741, end_date=20240710T133742
[2024-07-10T13:37:42.426+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 593 for task loading_into_db (could not open file "/opt/***/dags/charachteristics.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 1490)
[2024-07-10T13:37:42.445+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T13:37:42.461+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T13:37:42.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
