[2024-07-10T13:29:56.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T13:29:56.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T13:29:56.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T13:29:56.703+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 8
[2024-07-10T13:29:57.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): loading_into_db> on 2024-07-09 00:00:00+00:00
[2024-07-10T13:29:57.444+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1454) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T13:29:57.451+0000] {standard_task_runner.py:63} INFO - Started process 1463 to run task
[2024-07-10T13:29:57.441+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'loading_into_db', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '591', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv80oyjaw']
[2024-07-10T13:29:57.461+0000] {standard_task_runner.py:91} INFO - Job 591: Subtask loading_into_db
[2024-07-10T13:29:58.760+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [running]> on host afe5e479c9b4
[2024-07-10T13:29:59.163+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='loading_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T13:29:59.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T13:29:59.696+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T13:29:59.698+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 66, in load_charachteristics
    with open(r'C:\Users\User\Downloads\SpaceX project\dags\charachteristics.csv','r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Downloads\\SpaceX project\\dags\\charachteristics.csv'
[2024-07-10T13:29:59.747+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=loading_into_db, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T132956, end_date=20240710T132959
[2024-07-10T13:29:59.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 591 for task loading_into_db ([Errno 2] No such file or directory: 'C:\\Users\\User\\Downloads\\SpaceX project\\dags\\charachteristics.csv'; 1463)
[2024-07-10T13:29:59.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T13:29:59.868+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T13:29:59.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
