[2024-07-10T04:25:31.326+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T04:25:31.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T04:25:31.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T04:25:31.358+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-07-10T04:25:31.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): load_charachteristics> on 2024-07-09 00:00:00+00:00
[2024-07-10T04:25:31.380+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T04:25:31.382+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-07-10T04:25:31.382+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'load_charachteristics', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '555', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8xgl3jn8']
[2024-07-10T04:25:31.384+0000] {standard_task_runner.py:91} INFO - Job 555: Subtask load_charachteristics
[2024-07-10T04:25:31.433+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [running]> on host f565c82ff71d
[2024-07-10T04:25:31.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='load_charachteristics' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T04:25:31.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T04:25:31.534+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS charachteristics(
                id INT PRIMARY KEY,
                mass INT,
                diameter FLOAT,
                height FLOAT,
                cost_per_launch INT
            );
        
[2024-07-10T04:25:31.543+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-10T04:25:31.552+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-10T04:25:31.553+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T04:25:31.554+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "172.18.0.7", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-07-10T04:25:31.564+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=load_charachteristics, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T042531, end_date=20240710T042531
[2024-07-10T04:25:31.576+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 555 for task load_charachteristics (connection to server at "172.18.0.7", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 101)
[2024-07-10T04:25:31.597+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T04:25:31.606+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
