[2024-07-10T12:01:45.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T12:01:45.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T12:01:45.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T12:01:45.360+0000] {taskinstance.py:2306} INFO - Starting attempt 22 of 26
[2024-07-10T12:01:45.397+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): load_charachteristics> on 2024-07-09 00:00:00+00:00
[2024-07-10T12:01:45.421+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=782) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T12:01:45.435+0000] {standard_task_runner.py:63} INFO - Started process 784 to run task
[2024-07-10T12:01:45.445+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'load_charachteristics', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '581', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcyagw1i8']
[2024-07-10T12:01:45.457+0000] {standard_task_runner.py:91} INFO - Job 581: Subtask load_charachteristics
[2024-07-10T12:01:46.449+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [running]> on host afe5e479c9b4
[2024-07-10T12:01:46.609+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='load_charachteristics' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T12:01:46.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T12:01:46.636+0000] {sql.py:276} INFO - Executing: 
            COPY charachteristics(id,mass,diameter,height,cost_per_launch)
            FROM '/opt/***/dags/output.csv'
            DELIMITER ','
            CSV HEADER;
        
[2024-07-10T12:01:46.650+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-10T12:01:46.665+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-10T12:01:46.675+0000] {sql.py:487} INFO - Running statement: 
            COPY charachteristics(id,mass,diameter,height,cost_per_launch)
            FROM '/opt/***/dags/output.csv'
            DELIMITER ','
            CSV HEADER;
        , parameters: None
[2024-07-10T12:01:46.691+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T12:01:46.692+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/dags/output.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2024-07-10T12:01:46.709+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=load_charachteristics, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T120145, end_date=20240710T120146
[2024-07-10T12:01:46.724+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 581 for task load_charachteristics (could not open file "/opt/***/dags/output.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 784)
[2024-07-10T12:01:46.764+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T12:01:46.977+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T12:01:46.980+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
