[2024-07-10T14:55:54.483+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T14:55:55.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.transform scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T14:55:55.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.transform scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T14:55:55.364+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 9
[2024-07-10T14:55:55.397+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-07-09 00:00:00+00:00
[2024-07-10T14:55:55.428+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=752) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T14:55:55.436+0000] {standard_task_runner.py:63} INFO - Started process 754 to run task
[2024-07-10T14:55:55.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'transform', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9mgwv62z']
[2024-07-10T14:55:55.443+0000] {standard_task_runner.py:91} INFO - Job 604: Subtask transform
[2024-07-10T14:55:55.606+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.transform scheduled__2024-07-09T00:00:00+00:00 [running]> on host 1831119bf87f
[2024-07-10T14:55:55.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T14:55:55.866+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T14:55:56.000+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T14:55:56.001+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 43, in transform
    df1.to_csv('/mnt/c/Users/User/Downloads/SpaceX_project/output.csv', index=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/mnt/c/Users/User/Downloads/SpaceX_project'
[2024-07-10T14:55:56.036+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=transform, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T145555, end_date=20240710T145556
[2024-07-10T14:55:56.059+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 604 for task transform (Cannot save file into a non-existent directory: '/mnt/c/Users/User/Downloads/SpaceX_project'; 754)
[2024-07-10T14:55:56.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T14:55:56.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
